name: chttpractice

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        - "service-healthy"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/chttpracticedb
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts

  db:
    image: postgres:latest
    container_name: chttpracticedb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chttpracticedb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./logs:/var/log/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chttpracticedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
